<a href="https://colab.research.google.com/github/xhang24/20s_ma573/blob/master/src/hw8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from scipy.linalg import solve
def solve_function(e,interval_num):
  r=e*(interval_num**2)
  t=r
  s=2*r+1
  Rhf=np.linspace(0, 1, num=interval_num+1, endpoint=True)
  Rhf[-1]=0
  Lh=np.zeros((interval_num+1,interval_num+1))
  Lh[0,0]=1
  Lh[-1,-1]=1
  for i in range(interval_num-1):
    Lh[i+1,i]=-r
    Lh[i+1,i+1]=s
    Lh[i+1,i+2]=-t
  uh=solve(Lh,Rhf)
  return uh

In [16]:
solve_function(10**(-10),5)

array([0. , 0.2, 0.4, 0.6, 0.8, 0. ])

In [17]:
CFD=solve_function(10**(-10),9)
CFD

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888888, 0.        ])

In [0]:
error_array=np.zeros(10)
Rhf=np.linspace(0, 1, num=10, endpoint=True)
for i in range(10):
  x=Rhf[i]
  e=10**(-10)
  u=x-(np.exp((x-1)/np.sqrt(e))-np.exp(-(x+1)/np.sqrt(e)))/(1-np.exp(-2/np.sqrt(e)))
  error=np.abs(u-CFD[i])
  error_array[i]=error

In [19]:
error_array

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       5.55111512e-17, 0.00000000e+00, 1.11022302e-16, 1.11022302e-16,
       8.09999989e-09, 0.00000000e+00])

and same as the proof said the cfd looks better than fem. 
Compared error array with the FDE error shown in the report.